### ISSUE TITLE
请问一下mv播放入口在哪里

### ISSUE THREAD

**Issue by crazyzjw** [huweigoodboy/SweetMusicPlayer#11]
如题.

**Comment by verehu** [comment]
@zjw592824304  在线搜索音乐后，有的歌曲后面有一个红色的video图标，点击就可以进行mv播放了。

**Comment by crazyzjw** [comment]
我发现..歌词乱码的..

**Comment by verehu** [comment]
@zjw592824304  是在线音乐吗？具体是那首歌呢？

**Comment by crazyzjw** [comment]
..本地的,我在qq音乐哪里下载的歌词中文都是乱码..在线的就只能有歌 没歌词

**Comment by verehu** [comment]
qq音乐的歌词好像是加密的，具体要下班看看才知道，我这边用的网易云下载的歌词。在线的百度的API由于资源问题可能有限，部分歌曲可能无法显示歌词，后续会加入其他API，比如网易云。

**Comment by verehu** [comment]
@zjw592824304  我查看了qq音乐的歌词文件，是无法解析的。播放器会根据百度API来在线匹配歌词，不会去解析qq音乐下载的歌词，未匹配到歌词的歌曲可以在播放界面手动搜索歌词。 目前这个issue先关闭，如果需要更丰富的API，请重新提一个issue。
